version: '3.8'

services:
  php:
    build: ./php
    container_name: php-container
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    image: nginx:1.24-alpine
    platform: linux/amd64
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: micro
      MYSQL_USER: micro_user
      MYSQL_PASSWORD: micro_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
  
  memcached:
    image: memcached:alpine
    container_name: memcached-container
    ports:
      - "11211:11211"
    networks:
      - app-network

  postfix:
    build:
      context: ./postfix
    container_name: postfix
    hostname: mail.local
    restart: always
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge