CREATE TABLE IF NOT EXISTS comments (
  id INT PRIMARY KEY AUTO_INCREMENT,
  text TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  userID INT NOT NULL,
  postID INT NOT NULL,
  FOREIGN KEY (userID) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (postID) REFERENCES posts(id) ON DELETE CASCADE
)