CREATE TABLE IF NOT EXISTS post_tag (
  postID INT,
  tagID INT ,
  FOREIGN KEY (postID) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (tagID) REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (postID, tagID)
)