CREATE TABLE IF NOT EXISTS subscription (
  id INT PRIMARY KEY AUTO_INCREMENT,
  content VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  endsAt DATETIME DEFAULT NULL,
  userID INT NOT NULL,
  FOREIGN KEY (userID) REFERENCES users(id) ON DELETE CASCADE
)