ALTER TABLE users
DROP COLUMN emailConfirmedAt,
ADD COLUMN subscription VARCHAR(255) DEFAULT NULL,
ADD COLUMN subscriptionStatus VARCHAR(50) DEFAULT NULL,
ADD COLUMN subscriptionCreatedAt DATETIME DEFAULT NULL,
ADD COLUMN subscriptionEndsAt DATETIME DEFAULT NULL